[discord]
token = "42069"
application_id = 662205347343237121
guild_id = 810536807761707118
admin_channel_id = 818753943642964011

[cleaning]
  image_cdn_allowlist = [ 
     "instagram.com",
     "imgur.com",
     "cdn.discordapp.com",
     "media.jipvankuijk.nl",
  ]

[[channel]]
  #channel2
  id = 1062789397893881956 
  keep_images = false
  max_message_age_in_h = 1

[[channel]]
  #general
  id = 810536807761707121 
  keep_images = true
  max_message_age_in_h = 0

